task 1 beta
htmlacademy-vue/1789017-pizza-1 pull request #1
Opened 2021-07-08 16:09 UTC by svenez

2021-07-08 16:53 UTC, mosinve commented on src/frontend/src/common/helpers.js
> +    return _.map(items, (item) => ({
При входном параметре со значением по умолчанию = [] смысл от использования `lodash.map` теряется, т.к. его "фишки" работа с любыми итерируемыми объектами, а не только с массивами и корректная обработка undefined в данном конкретном случае не используются.

2021-07-08 16:58 UTC, mosinve commented on src/frontend/src/common/helpers.js
> +import _ from "lodash";
При таком импорте в итоговый бандл затянется весь `lodash`

Good-practice импорта методов `lodash`, при котором работает tree-shaking:
```js
import map from 'lodash/map';
```

2021-07-08 17:23 UTC, mosinve commented on src/frontend/src/layouts/AppLayout.vue
> +import Index from "@/views/Index";
Лучше указывать расширение файла при импорте, т.к. в каталоге views лежат 2 файла index: `index.js` и `Index.vue`. В разных ОС это может иметь разный эффект при сборке проекта. 
Например в MacOS это дает ошибку при сборке, т.к пытается импортироваться пустой `index.js`

2021-07-09 03:47 UTC, mosinve requested changes
1. Сборка проекта падает с ошибкой на macos
2. Внести изменения в json с данными для пиццы
3. Отрефакторить проект с учетом внесенных данных.

2021-07-09 03:47 UTC, mosinve commented on src/frontend/src/views/Index.vue
> +    console.log({ pizza });
Забыл удалить перед коммитом?

2021-07-09 03:47 UTC, mosinve commented on src/frontend/package.json
> +    "path": "^0.12.7",
Установка дополнительных библиотек не предусмотрена.

2021-07-11 08:45 UTC, svenez commented on src/frontend/src/common/helpers.js
> +    return _.map(items, (item) => ({
учтено, файл хелпера больше ненужен, добавлены коды в стаб бэка

2021-07-11 08:46 UTC, svenez commented on src/frontend/src/common/helpers.js
> +import _ from "lodash";
удалены все  сторонние пакеты

2021-07-11 08:46 UTC, svenez commented on src/frontend/src/layouts/AppLayout.vue
> +import Index from "@/views/Index";
расширения добавлены

2021-07-11 08:46 UTC, svenez commented on src/frontend/src/views/Index.vue
> +    console.log({ pizza });
дебаг удален

2021-07-11 08:47 UTC, svenez commented on src/frontend/package.json
> +    "path": "^0.12.7",
сторонние пакеты удалены

2021-07-12 05:56 UTC, merged